version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: twine
    versions:
    - 3.4.0
    - 3.4.1
  - dependency-name: tqdm
    versions:
    - 4.56.1
